In [ ]:
pip install pandas openpyxl

In [1]:
import pandas as pd
pd.read_excel('/content/tar.xlsx') # JSW  (file 1)

,INVOICE DATE,ODN NO,Destination,Quantity,Frt/MT,Truck Number,SHIP TO PARTY NAME
0,2025-01-04,MH2403172739,GV01-VAPI-GUJARAT,28.74,898.00,GJ01KT2016,KESAR INFRA
1,2025-01-04,MH2403172279,GV01-VAPI-GUJARAT,28.34,898.00,GJ16AV7883,VAPI RMC LLP
2,2024-12-31,MH2403169659,MV21-Virar-MIRA ROAD,29.76,680.00,MH04HD7386,G M ASSOCIATES
3,2025-01-02,MH2403171156,MV19-Vasai-MIRA ROAD,29.78,610.99,MH04HD7386,CONCEPTUALADVISORY SERVICES LLP
4,2025-01-05,MH2403173386,MP43-Pawne-NAVI MUMBAI,29.72,413.00,MH04HD7386,NAVDEEP CONSTRUCTION CO.
...,...,...,...,...,...,...,...
413,2024-12-30,MH2403169024,GJ01-Ahmedabad-GUJARAT,33.96,2079.98,MH46CU1750,ROCK SOLID RMC
414,2025-01-04,MH2403172518,GJ09-Surat-GUJARAT,34.14,1319.99,MH46CU9559,PRAYOSHA BUILDCON
415,2025-01-01,MH2403170584,MH05-Thane-Thane,23.72,514.99,MH46F5445,HARSH CONSTRUCTIONS PRIVATE LIMITED
416,2025-01-02,MH2403171098,MM58-Mhape-NAVI MUMBAI,24.02,440.00,MH46F5445,PRISM JOHNSON LIMITED
417,2025-01-03,MH2403171824,MN29-Nerul-NAVI MUMBAI,24.04,411.00,MH46F5445,VISION INFRA

In [17]:
pd.read_excel('/content/test.xlsx') # MIS (file 2)

,LD DATE,Vehicle Number,Destination,Customer/Consignee,LD WT,Inv No,Rate/Ton
0,2025-01-04,GJ01KT2016,VAPI,KESAR INFRA,28.74,MH2403172739,898.0
1,2025-01-04,GJ16AV7883,VAPI,VAPI RMC LLP,28.34,MH2403172279,898.0
2,2024-12-31,MH04HD7386,VIRAR,G M ASSOCIATES,29.76,MH2403169659,680.0
3,2025-01-02,MH04HD7386,VASAI,CONCEPTUALADVISORY SERVIES,29.78,MH2403171156,611.0
4,2025-01-05,MH04HD7386,PAWANE,NAVDEEP CONSTRUCTION CO,29.72,MH2403173386,413.0
...,...,...,...,...,...,...,...
430,2024-12-30,MH46CU1750,KALOL,ROCK SOLID RMC,33.96,MH2403169024,0.0
431,2025-01-04,MH46CU9559,UDHANA,PRAYOSHA BUILDCON,34.14,MH2403172518,0.0
432,2025-01-01,MH46F5445,THANE,HARSH CONSTRUCTIONS PVT LD,23.72,MH2403170584,515.0
433,2025-01-02,MH46F5445,Mahape,PRISM JOHNSON LIMITED,24.02,MH2403171098,440.0
434,2025-01-03,MH46F5445,THANE,VISION INFRA,24.04,MH2403171824,515.0

In [18]:
pd.read_excel('/content/comparison_results.xlsx')

,INVOICE DATE,ODN NO,Destination,Quantity,Frt/MT,Truck Number,SHIP TO PARTY NAME,Quantity Match,Rate Match,Match Result
0,2025-01-04,MH2403172739,GV01-VAPI-GUJARAT,28.74,898.00,GJ01KT2016,KESAR INFRA,Match - Exact,Match - Exact,Full Match
1,2025-01-04,MH2403172279,GV01-VAPI-GUJARAT,28.34,898.00,GJ16AV7883,VAPI RMC LLP,Match - Exact,Match - Exact,Full Match
2,2024-12-31,MH2403169659,MV21-Virar-MIRA ROAD,29.76,680.00,MH04HD7386,G M ASSOCIATES,Match - Exact,Match - Exact,Full Match
3,2025-01-02,MH2403171156,MV19-Vasai-MIRA ROAD,29.78,610.99,MH04HD7386,CONCEPTUALADVISORY SERVICES LLP,Match - Exact,Mismatch (diff: 0.01),Full Match
4,2025-01-05,MH2403173386,MP43-Pawne-NAVI MUMBAI,29.72,413.00,MH04HD7386,NAVDEEP CONSTRUCTION CO.,Match - Exact,Match - Exact,Full Match
...,...,...,...,...,...,...,...,...,...,...
413,2024-12-30,MH2403169024,GJ01-Ahmedabad-GUJARAT,33.96,2079.98,MH46CU1750,ROCK SOLID RMC,Match - Exact,Mismatch (diff: 2079.98),Partial Match
414,2025-01-04,MH2403172518,GJ09-Surat-GUJARAT,34.14,1319.99,MH46CU9559,PRAYOSHA BUILDCON,Match - Exact,Mismatch (diff: 1319.99),Partial Match
415,2025-01-01,MH2403170584,MH05-Thane-Thane,23.72,514.99,MH46F5445,HARSH CONSTRUCTIONS PRIVATE LIMITED,Match - Exact,Mismatch (diff: 0.01),Full Match
416,2025-01-02,MH2403171098,MM58-Mhape-NAVI MUMBAI,24.02,440.00,MH46F5445,PRISM JOHNSON LIMITED,Match - Exact,Match - Exact,Full Match
417,2025-01-03,MH2403171824,MN29-Nerul-NAVI MUMBAI,24.04,411.00,MH46F5445,VISION INFRA,Match - Exact,Mismatch (diff: 104.00),Partial Match

In [14]:
pd.read_csv('/content/unused_rows.csv')

,LD DATE,Vehicle Number,Destination,Customer/Consignee,LD WT,Inv No,Rate/Ton
0,2024-12-29,MH04KF8255,PEN,MS.JSW GREEN CEMENT PVT LTD,34.46,MH2403168718,149.0
1,2024-12-29,MH04KF8655,PEN,MS.JSW GREEN CEMENT PVT LTD,34.30,MH2403168621,149.0
2,2024-12-31,MH04KF9522,PEN,MS.JSW GREEN CEMENT PVT LTD,34.80,MH2403167821,149.0
3,2024-12-31,MH04LE8520,WADA,GREENARE CRETE PVT LTD,34.16,TGM25INV028979,1565.0
4,2024-12-30,MH04LE8528,TALOJA,THAKUR INFRAPROJECTS PRIVATE LIMITED TALOJA,42.00,1034,1900.0
5,2024-12-31,MH04LE8541,Surat,MILLINNIUM INFRA SQUARE LLP,33.06,TGM25INV028931,783.0
6,2024-12-31,MH04LE8546,GANJAD,MEIL-MAIN CAMP,34.05,TGM25INV028720,1503.0
7,2024-12-31,MH04LE9520,Kanchad,BIGBLOCK BUILDING ELEMENTS PVT LTD KANCHAD,33.73,TGM25INV028939,1537.0
8,2024-12-30,MH04LE9668,KANJURMARG,S S CONSTRUCTION,45.00,1033,1900.0
9,2024-12-30,MH04LQ0073,MUMBAI,YM LANDMARK PRIVATE LIMITED,28.16,1027,650.0
10,2024-12-30,MH04LQ0078,BHIWANDI,RACHANA CONSTRUCTION LTD,32.10,MHN0082500000828,NaN
11,2024-12-31,MH04LQ8204,TALOJA,MULTI STOREY PROJECTS,34.53,1036,850.0
12,2024-12-30,MH04LQ8215,VASAI,CONCEPTUAL ADVISORY SERVICES LIP RMC,33.36,MHN0082500000813,NaN
13,2024-12-30,MH04LQ8859,VASAI,CONCEPTUAL ADVISORY SERVICES LIP RMC,33.01,MHN0082500000814,NaN
14,2024-12-31,MH04LQ8862,VIRAR,WONDER CEMENT LIMITED,32.90,TGM25INV028796,1590.0
15,2024-12-31,MH04LY0821,WADA,GREENARE CRETE PVT LTD,32.92,TGM25INV028978,1565.0
16,2024-12-31,MH04LY0822,VASAI,DINESHCHANDRA R AGRAWAL INFRACON PVT LTD,33.98,TGM25INV028907,1625.0
17,2024-12-31,MH04LY0823,Surat,CLASSIC DEVELOPERS,33.19,TGM25INV028838,783.0
18,2024-12-30,MH04LY0824,BHIWANDI,RACHANA CONSTRUCTION LTD,32.98,MHN0082500000827,NaN
19,2024-12-31,MH04LY0828,GANJAD,MEIL- MAIN CAMP,33.46,TGM25INV028908,1503.0
20,2024-12-31,MH04LY1321,CHORASI,SAHJANAND REALITY,34.43,TGM25INV028836,827.0
21,2024-12-30,MH04LY1322,JOGESHWARI,CONCRETECH INDIA,33.41,1028,1400.0
22,2024-12-31,MH04LY1323,CHORASI,SAHJANAND REALITY,33.50,TGM25INV028839,827.0
23,2024-12-30,MH46CL2099,Surat,AVADH LIFE SPACE PVT LTD,34.18,TGM25INV028663,783.0
24,2024-12-31,MH46CL2099,VIRAR,WONDER CEMENT LIMITED,33.71,TGM25INV028969,1590.0
25,2024-12-31,MH46CU1508,Surat,DHANUSHA CONSTRUCTION,33.78,TGM25INV028834,783.0

In [16]:
import pandas as pd
import numpy as np
from collections import Counter

def compare_excel_columns(file1, file2, column1, column2, quantity_col1, quantity_col2, rate_col1, rate_col2, output_file, unused_rows_file):
    # Read the Excel files
    df1 = pd.read_excel(file1)
    df2 = pd.read_excel(file2)

    # Check for duplicates in ODN NO column (file1)
    odn_no_counts = Counter(df1[column1])
    duplicates_file1 = {odn: count for odn, count in odn_no_counts.items() if count > 1}

    if duplicates_file1:
        print("Duplicate ODN NO values found in file1:")
        for odn, count in duplicates_file1.items():
            print(f"ODN NO: {odn}, Repeated: {count} times")
    else:
        print("No duplicate ODN NO values found in file1.")

    # Check for duplicates in Inv No column (file2)
    inv_no_counts = Counter(df2[column2])
    duplicates_file2 = {inv: count for inv, count in inv_no_counts.items() if count > 1}

    if duplicates_file2:
        print("\nDuplicate Inv No values found in file2:")
        for inv, count in duplicates_file2.items():
            print(f"Inv No: {inv}, Repeated: {count} times")
    else:
        print("\nNo duplicate Inv No values found in file2.")

    # Create a dictionary for faster searching
    search_dict = df2.set_index(column2).to_dict('index')

    # Create a set to keep track of used rows in df2
    used_rows = set()

    # Initialize lists to store results
    matched = []
    unmatched = []

    # Create new columns for match results
    df1['Quantity Match'] = ''
    df1['Rate Match'] = ''
    df1['Match Result'] = ''

    # Perform the comparison
    for idx, row in df1.iterrows():
        value = row[column1]
        if value in search_dict:
            used_rows.add(value)
            df2_row = search_dict[value]
            quantity_diff = abs(row[quantity_col1] - df2_row[quantity_col2])
            rate_diff = abs(row[rate_col1] - df2_row[rate_col2])

            # Check quantity match
            if quantity_diff <= 0.2:
                quantity_match = "Exact" if quantity_diff == 0 else f"Close (diff: {quantity_diff:.2f})"
                df1.at[idx, 'Quantity Match'] = f"Match - {quantity_match}"
            else:
                df1.at[idx, 'Quantity Match'] = f"Mismatch (diff: {quantity_diff:.2f})"

            # Check rate match
            if rate_diff == 0:
                rate_match = "Exact"
                df1.at[idx, 'Rate Match'] = f"Match - {rate_match}"
            elif 1 <= rate_diff <= 10:
                rate_match = f"Close (diff: {rate_diff:.2f})"
                df1.at[idx, 'Rate Match'] = f"Match - {rate_match}"
            else:
                df1.at[idx, 'Rate Match'] = f"Mismatch (diff: {rate_diff:.2f})"

            # Determine overall match result
            if quantity_diff <= 0.2 and rate_diff <= 10:
                df1.at[idx, 'Match Result'] = "Full Match"
                matched.append(f"Row {idx + 1} in {file1} - Full match for value '{value}' - Quantity: {quantity_match}, Rate: {rate_match}")
            else:
                df1.at[idx, 'Match Result'] = "Partial Match"
                unmatched.append({
                    'row_number': idx + 1,
                    'unmatched_value': value,
                    'quantity_diff': quantity_diff,
                    'rate_diff': rate_diff,
                    'row_details': row.to_dict()
                })
        else:
            df1.at[idx, 'Quantity Match'] = "No match found"
            df1.at[idx, 'Rate Match'] = "No match found"
            df1.at[idx, 'Match Result'] = "No match found"
            unmatched.append({
                'row_number': idx + 1,
                'unmatched_value': value,
                'row_details': row.to_dict()
            })

    # Save the results to a new Excel file
    df1.to_excel(output_file, index=False)

    # Find unused rows in df2
    unused_df = df2[~df2[column2].isin(used_rows)]

    # Save unused rows to a separate CSV file
    unused_df.to_csv(unused_rows_file, index=False)

    # Print matched results
    print("\nMatched Results:")
    for result in matched:
        print(result)

    # Print unmatched results with full row details
    print("\nUnmatched Results:")
    for item in unmatched:
        print(f"Row {item['row_number']} in {file1} - Partial or no match for value '{item['unmatched_value']}'")
        if 'quantity_diff' in item:
            print(f"Quantity difference: {item['quantity_diff']:.2f}")
        if 'rate_diff' in item:
            print(f"Rate difference: {item['rate_diff']:.2f}")
        print("Row Details:")
        for key, value in item['row_details'].items():
            print(f"  {key}: {value}")
        print()

    # Print summary
    print(f"Total Rows in {file1}: {len(df1)}")
    print(f"Fully Matched Rows: {len(matched)}")
    print(f"Partially Matched or Unmatched Rows: {len(unmatched)}")
    print(f"Unused Rows in {file2}: {len(unused_df)}")
    print(f"Results saved to {output_file}")
    print(f"Unused rows from {file2} saved to {unused_rows_file}")

# File paths and column names
file1 = '/content/tar.xlsx'
file2 = '/content/test.xlsx'
column1 = 'ODN NO'  # Column name in the first file
column2 = 'Inv No'  # Column name in the second file
quantity_col1 = 'Quantity'  # Quantity column name in the first file
quantity_col2 = 'LD WT'  # Quantity column name in the second file
rate_col1 = 'Frt/MT'  # Rate column name in the first file
rate_col2 = 'Rate/Ton'  # Rate column name in the second file
output_file = '/content/comparison_results.xlsx'
unused_rows_file = '/content/unused_rows.csv'

compare_excel_columns(file1, file2, column1, column2, quantity_col1, quantity_col2, rate_col1, rate_col2, output_file, unused_rows_file)

# Print the contents of the unused rows file
print("\nContents of the unused rows file:")
unused_df = pd.read_csv(unused_rows_file)
print(unused_df)

No duplicate ODN NO values found in file1.

No duplicate Inv No values found in file2.

Matched Results:
Row 1 in /content/tar.xlsx - Full match for value 'MH2403172739' - Quantity: Exact, Rate: Exact
Row 2 in /content/tar.xlsx - Full match for value 'MH2403172279' - Quantity: Exact, Rate: Exact
Row 3 in /content/tar.xlsx - Full match for value 'MH2403169659' - Quantity: Exact, Rate: Exact
Row 4 in /content/tar.xlsx - Full match for value 'MH2403171156' - Quantity: Exact, Rate: Exact
Row 5 in /content/tar.xlsx - Full match for value 'MH2403173386' - Quantity: Exact, Rate: Exact
Row 6 in /content/tar.xlsx - Full match for value 'MH2403169926' - Quantity: Exact, Rate: Exact
Row 7 in /content/tar.xlsx - Full match for value 'MH2403171588' - Quantity: Exact, Rate: Exact
Row 8 in /content/tar.xlsx - Full match for value 'MH2403172802' - Quantity: Exact, Rate: Exact
Row 9 in /content/tar.xlsx - Full match for value 'MH2403170569' - Quantity: Exact, Rate: Exact
Row 10 in /content/tar.xlsx - Full match for value 'MH2403170960' - Quantity: Exact, Rate: Exact
Row 11 in /content/tar.xlsx - Full match for value 'MH2403172035' - Quantity: Exact, Rate: Exact
Row 12 in /content/tar.xlsx - Full match for value 'MH2403173469' - Quantity: Exact, Rate: Exact
Row 13 in /content/tar.xlsx - Full match for value 'MH2403169243' - Quantity: Exact, Rate: Exact
Row 14 in /content/tar.xlsx - Full match for value 'MH2403170608' - Quantity: Exact, Rate: Exact
Row 15 in /content/tar.xlsx - Full match for value 'MH2403171635' - Quantity: Exact, Rate: Exact
Row 16 in /content/tar.xlsx - Full match for value 'MH2403168824' - Quantity: Exact, Rate: Exact
Row 17 in /content/tar.xlsx - Full match for value 'MH2403171493' - Quantity: Exact, Rate: Exact
Row 18 in /content/tar.xlsx - Full match for value 'MH2403171948' - Quantity: Exact, Rate: Exact
Row 19 in /content/tar.xlsx - Full match for value 'MH2403173348' - Quantity: Exact, Rate: Exact
Row 20 in /content/tar.xlsx - Full match for value 'MH2403168918' - Quantity: Exact, Rate: Exact
Row 21 in /content/tar.xlsx - Full match for value 'MH2403169237' - Quantity: Exact, Rate: Exact
Row 22 in /content/tar.xlsx - Full match for value 'MH2403169991' - Quantity: Exact, Rate: Exact
Row 23 in /content/tar.xlsx - Full match for value 'MH2403171385' - Quantity: Exact, Rate: Exact
Row 24 in /content/tar.xlsx - Full match for value 'MH2403171886' - Quantity: Exact, Rate: Exact
Row 25 in /content/tar.xlsx - Full match for value 'MH2403172727' - Quantity: Exact, Rate: Exact
Row 26 in /content/tar.xlsx - Full match for value 'MH2403173174' - Quantity: Exact, Rate: Exact
Row 27 in /content/tar.xlsx - Full match for value 'MH2403169138' - Quantity: Exact, Rate: Exact
Row 28 in /content/tar.xlsx - Full match for value 'MH2403170429' - Quantity: Exact, Rate: Exact
Row 29 in /content/tar.xlsx - Full match for value 'MH2403171164' - Quantity: Exact, Rate: Exact
Row 31 in /content/tar.xlsx - Full match for value 'MH2403173009' - Quantity: Exact, Rate: Exact
Row 32 in /content/tar.xlsx - Full match for value 'MH2403168872' - Quantity: Exact, Rate: Exact
Row 33 in /content/tar.xlsx - Full match for value 'MH2403169696' - Quantity: Exact, Rate: Exact
Row 34 in /content/tar.xlsx - Full match for value 'MH2403170592' - Quantity: Exact, Rate: Exact
Row 35 in /content/tar.xlsx - Full match for value 'MH2403171065' - Quantity: Exact, Rate: Exact
Row 36 in /content/tar.xlsx - Full match for value 'MH2403172750' - Quantity: Exact, Rate: Exact
Row 37 in /content/tar.xlsx - Full match for value 'MH2403169113' - Quantity: Exact, Rate: Close (diff: 6.01)
Row 38 in /content/tar.xlsx - Full match for value 'MH2403169986' - Quantity: Exact, Rate: Exact
Row 39 in /content/tar.xlsx - Full match for value 'MH2403171064' - Quantity: Exact, Rate: Exact
Row 40 in /content/tar.xlsx - Full match for value 'MH2403171592' - Quantity: Exact, Rate: Exact
Row 41 in /content/tar.xlsx - Full match for value 'MH2403169260' - Quantity: Exact, Rate: Exact
Row 42 in /content/tar.xlsx - Full match for value 'MH2403170121' - Quantity: Exact, Rate: Exact
Row 43 in /content/tar.xlsx - Full match for value 'MH2403172776' - Quantity: Exact, Rate: Exact
Row 44 in /content/tar.xlsx - Full match for value 'MH2403169402' - Quantity: Exact, Rate: Exact
Row 45 in /content/tar.xlsx - Full match for value 'MH2403170604' - Quantity: Exact, Rate: Exact
Row 46 in /content/tar.xlsx - Full match for value 'MH2403171649' - Quantity: Exact, Rate: Exact
Row 47 in /content/tar.xlsx - Full match for value 'MH2403172812' - Quantity: Exact, Rate: Exact
Row 48 in /content/tar.xlsx - Full match for value 'MH2403169190' - Quantity: Exact, Rate: Exact
Row 49 in /content/tar.xlsx - Full match for value 'MH2403171057' - Quantity: Exact, Rate: Exact
Row 50 in /content/tar.xlsx - Full match for value 'MH2403169385' - Quantity: Exact, Rate: Exact
Row 51 in /content/tar.xlsx - Full match for value 'MH2403171068' - Quantity: Exact, Rate: Exact
Row 52 in /content/tar.xlsx - Full match for value 'MH2403172664' - Quantity: Exact, Rate: Exact
Row 54 in /content/tar.xlsx - Full match for value 'MH2403170300' - Quantity: Exact, Rate: Exact
Row 55 in /content/tar.xlsx - Full match for value 'MH2403170966' - Quantity: Exact, Rate: Exact
Row 56 in /content/tar.xlsx - Full match for value 'MH2403171462' - Quantity: Exact, Rate: Exact
Row 57 in /content/tar.xlsx - Full match for value 'MH2403172781' - Quantity: Exact, Rate: Exact
Row 60 in /content/tar.xlsx - Full match for value 'MH2403172659' - Quantity: Exact, Rate: Exact
Row 61 in /content/tar.xlsx - Full match for value 'MH2403168969' - Quantity: Exact, Rate: Exact
Row 62 in /content/tar.xlsx - Full match for value 'MH2403169818' - Quantity: Exact, Rate: Exact
Row 63 in /content/tar.xlsx - Full match for value 'MH2403171299' - Quantity: Exact, Rate: Exact
Row 64 in /content/tar.xlsx - Full match for value 'MH2403170519' - Quantity: Exact, Rate: Exact
Row 65 in /content/tar.xlsx - Full match for value 'MH2403171589' - Quantity: Exact, Rate: Exact
Row 68 in /content/tar.xlsx - Full match for value 'MH2403171023' - Quantity: Exact, Rate: Exact
Row 69 in /content/tar.xlsx - Full match for value 'MH2403172764' - Quantity: Exact, Rate: Exact
Row 70 in /content/tar.xlsx - Full match for value 'MH2403173151' - Quantity: Exact, Rate: Exact
Row 74 in /content/tar.xlsx - Full match for value 'MH2403169643' - Quantity: Exact, Rate: Exact
Row 75 in /content/tar.xlsx - Full match for value 'MH2403172893' - Quantity: Exact, Rate: Exact
Row 77 in /content/tar.xlsx - Full match for value 'MH2403170694' - Quantity: Exact, Rate: Exact
Row 78 in /content/tar.xlsx - Full match for value 'MH2403171468' - Quantity: Exact, Rate: Exact
Row 80 in /content/tar.xlsx - Full match for value 'MH2403168935' - Quantity: Exact, Rate: Exact
Row 81 in /content/tar.xlsx - Full match for value 'MH2403171661' - Quantity: Exact, Rate: Exact
Row 82 in /content/tar.xlsx - Full match for value 'MH2403170607' - Quantity: Exact, Rate: Exact
Row 83 in /content/tar.xlsx - Full match for value 'MH2403171647' - Quantity: Exact, Rate: Exact
Row 84 in /content/tar.xlsx - Full match for value 'MH2403172560' - Quantity: Exact, Rate: Exact
Row 85 in /content/tar.xlsx - Full match for value 'MH2403168859' - Quantity: Exact, Rate: Exact
Row 86 in /content/tar.xlsx - Full match for value 'MH2403173375' - Quantity: Exact, Rate: Exact
Row 88 in /content/tar.xlsx - Full match for value 'MH2403173410' - Quantity: Exact, Rate: Exact
Row 92 in /content/tar.xlsx - Full match for value 'MH2403173477' - Quantity: Exact, Rate: Exact
Row 93 in /content/tar.xlsx - Full match for value 'MH2403171540' - Quantity: Exact, Rate: Exact
Row 94 in /content/tar.xlsx - Full match for value 'MH2403169288' - Quantity: Exact, Rate: Exact
Row 95 in /content/tar.xlsx - Full match for value 'MH2403170152' - Quantity: Exact, Rate: Exact
Row 96 in /content/tar.xlsx - Full match for value 'MH2403171311' - Quantity: Exact, Rate: Exact
Row 98 in /content/tar.xlsx - Full match for value 'MH2403173482' - Quantity: Exact, Rate: Exact
Row 99 in /content/tar.xlsx - Full match for value 'MH2403168945' - Quantity: Exact, Rate: Exact
Row 100 in /content/tar.xlsx - Full match for value 'MH2403171074' - Quantity: Exact, Rate: Exact
Row 101 in /content/tar.xlsx - Full match for value 'MH2403171899' - Quantity: Exact, Rate: Exact
Row 102 in /content/tar.xlsx - Full match for value 'MH2403172748' - Quantity: Exact, Rate: Exact
Row 103 in /content/tar.xlsx - Full match for value 'MH2403169557' - Quantity: Exact, Rate: Exact
Row 104 in /content/tar.xlsx - Full match for value 'MH2403172128' - Quantity: Exact, Rate: Exact
Row 105 in /content/tar.xlsx - Full match for value 'MH2403172778' - Quantity: Exact, Rate: Exact
Row 106 in /content/tar.xlsx - Full match for value 'MH2403173485' - Quantity: Exact, Rate: Exact
Row 107 in /content/tar.xlsx - Full match for value 'MH2403168807' - Quantity: Exact, Rate: Exact
Row 108 in /content/tar.xlsx - Full match for value 'MH2403169312' - Quantity: Exact, Rate: Exact
Row 109 in /content/tar.xlsx - Full match for value 'MH2403170775' - Quantity: Exact, Rate: Exact
Row 110 in /content/tar.xlsx - Full match for value 'MH2403171502' - Quantity: Exact, Rate: Exact
Row 112 in /content/tar.xlsx - Full match for value 'MH2403172330' - Quantity: Exact, Rate: Exact
Row 117 in /content/tar.xlsx - Full match for value 'MH2403173381' - Quantity: Exact, Rate: Exact
Row 118 in /content/tar.xlsx - Full match for value 'MH2403169779' - Quantity: Exact, Rate: Exact
Row 119 in /content/tar.xlsx - Full match for value 'MH2403169280' - Quantity: Exact, Rate: Exact
Row 120 in /content/tar.xlsx - Full match for value 'MH2403170556' - Quantity: Exact, Rate: Exact
Row 121 in /content/tar.xlsx - Full match for value 'MH2403171174' - Quantity: Exact, Rate: Exact
Row 122 in /content/tar.xlsx - Full match for value 'MH2403172552' - Quantity: Exact, Rate: Exact
Row 124 in /content/tar.xlsx - Full match for value 'MH2403169626' - Quantity: Exact, Rate: Exact
Row 126 in /content/tar.xlsx - Full match for value 'MH2403169769' - Quantity: Exact, Rate: Exact
Row 127 in /content/tar.xlsx - Full match for value 'MH2403172587' - Quantity: Exact, Rate: Exact
Row 130 in /content/tar.xlsx - Full match for value 'MH2403170699' - Quantity: Exact, Rate: Exact
Row 133 in /content/tar.xlsx - Full match for value 'MH2403170619' - Quantity: Exact, Rate: Exact
Row 135 in /content/tar.xlsx - Full match for value 'MH2403169331' - Quantity: Exact, Rate: Exact
Row 136 in /content/tar.xlsx - Full match for value 'MH2403170460' - Quantity: Exact, Rate: Exact
Row 137 in /content/tar.xlsx - Full match for value 'MH2403170963' - Quantity: Exact, Rate: Exact
Row 138 in /content/tar.xlsx - Full match for value 'MH2403172737' - Quantity: Exact, Rate: Exact
Row 139 in /content/tar.xlsx - Full match for value 'MH2403173476' - Quantity: Exact, Rate: Exact
Row 141 in /content/tar.xlsx - Full match for value 'MH2403171771' - Quantity: Exact, Rate: Exact
Row 142 in /content/tar.xlsx - Full match for value 'MH2403173194' - Quantity: Exact, Rate: Exact
Row 143 in /content/tar.xlsx - Full match for value 'MH2403172957' - Quantity: Exact, Rate: Exact
Row 144 in /content/tar.xlsx - Full match for value 'MH2403172964' - Quantity: Exact, Rate: Exact
Row 147 in /content/tar.xlsx - Full match for value 'MH2403170588' - Quantity: Exact, Rate: Exact
Row 149 in /content/tar.xlsx - Full match for value 'MH2403172509' - Quantity: Exact, Rate: Exact
Row 151 in /content/tar.xlsx - Full match for value 'MH2403172003' - Quantity: Exact, Rate: Exact
Row 152 in /content/tar.xlsx - Full match for value 'MH2403171014' - Quantity: Exact, Rate: Exact
Row 155 in /content/tar.xlsx - Full match for value 'MH2403170518' - Quantity: Exact, Rate: Exact
Row 156 in /content/tar.xlsx - Full match for value 'MH2403170962' - Quantity: Exact, Rate: Exact
Row 157 in /content/tar.xlsx - Full match for value 'MH2403171259' - Quantity: Exact, Rate: Exact
Row 159 in /content/tar.xlsx - Full match for value 'MH2403169281' - Quantity: Exact, Rate: Exact
Row 160 in /content/tar.xlsx - Full match for value 'MH2403170445' - Quantity: Exact, Rate: Exact
Row 161 in /content/tar.xlsx - Full match for value 'MH2403170722' - Quantity: Exact, Rate: Exact
Row 162 in /content/tar.xlsx - Full match for value 'MH2403173289' - Quantity: Exact, Rate: Exact
Row 163 in /content/tar.xlsx - Full match for value 'MH2403171504' - Quantity: Exact, Rate: Exact
Row 164 in /content/tar.xlsx - Full match for value 'MH2403172544' - Quantity: Exact, Rate: Exact
Row 165 in /content/tar.xlsx - Full match for value 'MH2403169403' - Quantity: Exact, Rate: Exact
Row 166 in /content/tar.xlsx - Full match for value 'MH2403170698' - Quantity: Exact, Rate: Exact
Row 167 in /content/tar.xlsx - Full match for value 'MH2403172616' - Quantity: Exact, Rate: Exact
Row 168 in /content/tar.xlsx - Full match for value 'MH2403170111' - Quantity: Exact, Rate: Exact
Row 169 in /content/tar.xlsx - Full match for value 'MH2403172264' - Quantity: Exact, Rate: Exact
Row 171 in /content/tar.xlsx - Full match for value 'MH2403170667' - Quantity: Exact, Rate: Exact
Row 172 in /content/tar.xlsx - Full match for value 'MH2403171770' - Quantity: Exact, Rate: Exact
Row 173 in /content/tar.xlsx - Full match for value 'MH2403173209' - Quantity: Exact, Rate: Exact
Row 174 in /content/tar.xlsx - Full match for value 'MH2403168931' - Quantity: Exact, Rate: Exact
Row 175 in /content/tar.xlsx - Full match for value 'MH2403169580' - Quantity: Exact, Rate: Exact
Row 176 in /content/tar.xlsx - Full match for value 'MH2403170561' - Quantity: Exact, Rate: Exact
Row 177 in /content/tar.xlsx - Full match for value 'MH2403170987' - Quantity: Exact, Rate: Exact
Row 178 in /content/tar.xlsx - Full match for value 'MH2403172514' - Quantity: Exact, Rate: Exact
Row 179 in /content/tar.xlsx - Full match for value 'MH2403173296' - Quantity: Exact, Rate: Exact
Row 180 in /content/tar.xlsx - Full match for value 'MH2403170526' - Quantity: Exact, Rate: Exact
Row 181 in /content/tar.xlsx - Full match for value 'MH2403170116' - Quantity: Exact, Rate: Exact
Row 182 in /content/tar.xlsx - Full match for value 'MH2403171506' - Quantity: Exact, Rate: Exact
Row 183 in /content/tar.xlsx - Full match for value 'MH2403170114' - Quantity: Exact, Rate: Exact
Row 184 in /content/tar.xlsx - Full match for value 'MH2403171523' - Quantity: Exact, Rate: Exact
Row 185 in /content/tar.xlsx - Full match for value 'MH2403168841' - Quantity: Exact, Rate: Exact
Row 187 in /content/tar.xlsx - Full match for value 'MH2403172344' - Quantity: Exact, Rate: Exact
Row 188 in /content/tar.xlsx - Full match for value 'MH2403169265' - Quantity: Exact, Rate: Exact
Row 189 in /content/tar.xlsx - Full match for value 'MH2403170571' - Quantity: Exact, Rate: Exact
Row 190 in /content/tar.xlsx - Full match for value 'MH2403171544' - Quantity: Exact, Rate: Exact
Row 191 in /content/tar.xlsx - Full match for value 'MH2403172348' - Quantity: Exact, Rate: Exact
Row 192 in /content/tar.xlsx - Full match for value 'MH2403172966' - Quantity: Exact, Rate: Exact
Row 193 in /content/tar.xlsx - Full match for value 'MH2403170921' - Quantity: Exact, Rate: Exact
Row 194 in /content/tar.xlsx - Full match for value 'MH2403170602' - Quantity: Exact, Rate: Exact
Row 197 in /content/tar.xlsx - Full match for value 'MH2403168987' - Quantity: Exact, Rate: Exact
Row 198 in /content/tar.xlsx - Full match for value 'MH2403170436' - Quantity: Exact, Rate: Exact
Row 199 in /content/tar.xlsx - Full match for value 'MH2403170945' - Quantity: Exact, Rate: Exact
Row 200 in /content/tar.xlsx - Full match for value 'MH2403171880' - Quantity: Exact, Rate: Exact
Row 201 in /content/tar.xlsx - Full match for value 'MH2403172206' - Quantity: Exact, Rate: Exact
Row 202 in /content/tar.xlsx - Full match for value 'MH2403168934' - Quantity: Exact, Rate: Exact
Row 203 in /content/tar.xlsx - Full match for value 'MH2403171676' - Quantity: Exact, Rate: Exact
Row 205 in /content/tar.xlsx - Full match for value 'MH2403170717' - Quantity: Exact, Rate: Exact
Row 206 in /content/tar.xlsx - Full match for value 'MH2403173213' - Quantity: Exact, Rate: Exact
Row 207 in /content/tar.xlsx - Full match for value 'MH2403169774' - Quantity: Exact, Rate: Exact
Row 209 in /content/tar.xlsx - Full match for value 'MH2403170959' - Quantity: Exact, Rate: Exact
Row 210 in /content/tar.xlsx - Full match for value 'MH2403172260' - Quantity: Exact, Rate: Exact
Row 211 in /content/tar.xlsx - Full match for value 'MH2403170668' - Quantity: Exact, Rate: Exact
Row 212 in /content/tar.xlsx - Full match for value 'MH2403168988' - Quantity: Exact, Rate: Exact
Row 213 in /content/tar.xlsx - Full match for value 'MH2403170351' - Quantity: Exact, Rate: Exact
Row 214 in /content/tar.xlsx - Full match for value 'MH2403170855' - Quantity: Exact, Rate: Close (diff: 2.07)
Row 215 in /content/tar.xlsx - Full match for value 'MH2403171145' - Quantity: Exact, Rate: Close (diff: 2.07)
Row 216 in /content/tar.xlsx - Full match for value 'MH2403171892' - Quantity: Exact, Rate: Close (diff: 2.07)
Row 217 in /content/tar.xlsx - Full match for value 'MH2403172882' - Quantity: Exact, Rate: Exact
Row 220 in /content/tar.xlsx - Full match for value 'MH2403169432' - Quantity: Exact, Rate: Exact
Row 221 in /content/tar.xlsx - Full match for value 'MH2403170719' - Quantity: Exact, Rate: Exact
Row 222 in /content/tar.xlsx - Full match for value 'MH2403169094' - Quantity: Exact, Rate: Exact
Row 223 in /content/tar.xlsx - Full match for value 'MH2403169951' - Quantity: Exact, Rate: Exact
Row 224 in /content/tar.xlsx - Full match for value 'MH2403170737' - Quantity: Exact, Rate: Exact
Row 225 in /content/tar.xlsx - Full match for value 'MH2403171292' - Quantity: Exact, Rate: Exact
Row 226 in /content/tar.xlsx - Full match for value 'MH2403171891' - Quantity: Exact, Rate: Exact
Row 227 in /content/tar.xlsx - Full match for value 'MH2403172619' - Quantity: Exact, Rate: Exact
Row 228 in /content/tar.xlsx - Full match for value 'MH2403173155' - Quantity: Exact, Rate: Exact
Row 230 in /content/tar.xlsx - Full match for value 'MH2403170578' - Quantity: Exact, Rate: Exact
Row 231 in /content/tar.xlsx - Full match for value 'MH2403171095' - Quantity: Exact, Rate: Exact
Row 232 in /content/tar.xlsx - Full match for value 'MH2403171955' - Quantity: Exact, Rate: Exact
Row 233 in /content/tar.xlsx - Full match for value 'MH2403172798' - Quantity: Exact, Rate: Exact
Row 234 in /content/tar.xlsx - Full match for value 'MH2403172214' - Quantity: Exact, Rate: Exact
Row 235 in /content/tar.xlsx - Full match for value 'MH2403172215' - Quantity: Exact, Rate: Exact
Row 237 in /content/tar.xlsx - Full match for value 'MH2403170521' - Quantity: Exact, Rate: Exact
Row 238 in /content/tar.xlsx - Full match for value 'MH2403172429' - Quantity: Exact, Rate: Exact
Row 239 in /content/tar.xlsx - Full match for value 'MH2403173475' - Quantity: Exact, Rate: Exact
Row 240 in /content/tar.xlsx - Full match for value 'MH2403169219' - Quantity: Exact, Rate: Exact
Row 241 in /content/tar.xlsx - Full match for value 'MH2403168871' - Quantity: Exact, Rate: Exact
Row 242 in /content/tar.xlsx - Full match for value 'MH2403169248' - Quantity: Exact, Rate: Exact
Row 244 in /content/tar.xlsx - Full match for value 'MH2403171489' - Quantity: Exact, Rate: Exact
Row 245 in /content/tar.xlsx - Full match for value 'MH2403172064' - Quantity: Exact, Rate: Exact
Row 246 in /content/tar.xlsx - Full match for value 'MH2403173481' - Quantity: Exact, Rate: Exact
Row 248 in /content/tar.xlsx - Full match for value 'MH2403170161' - Quantity: Exact, Rate: Exact
Row 250 in /content/tar.xlsx - Full match for value 'MH2403171466' - Quantity: Exact, Rate: Exact
Row 251 in /content/tar.xlsx - Full match for value 'MH2403170473' - Quantity: Exact, Rate: Exact
Row 252 in /content/tar.xlsx - Full match for value 'MH2403171627' - Quantity: Exact, Rate: Exact